language: node_js

branches:
  only:
    - frontend
    - backend

node_js:
  - 8

script:
  - yarn test

notifications:
  email:
    on_failure: change

after_success:
  - yarn coveralls

cache:
  yarn: true
  directories:
    - node_modules
