language: node_js

branches:
  only:
    - master

node_js:
  - 8

script:
  - yarn test
  - yarn build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x ./internals/netlify.sh

notifications:
  email:
    on_failure: change

after_success:
  - yarn coveralls
  - ./internals/netlify.sh

cache:
  yarn: true
  directories:
    - node_modules
